### PR TITLE
Fix browser-check test

### PR DESCRIPTION
**Pull request by brichet**
Related to https://github.com/jupyterlab/jupyterlab/issues/17079

Thanks @trungleduc for the pointer.

### CODE REVIEW

**Comment by jtpio** [comment]
FYI there is likely a fix coming in the next JupyterLab `4.3.4`: https://github.com/jupyterlab/jupyterlab/pull/17094

**Comment by brichet** [comment]
> FYI there is likely a fix coming in the next JupyterLab `4.3.4`: [jupyterlab/jupyterlab#17094](https://github.com/jupyterlab/jupyterlab/pull/17094)

:tada: nice, so maybe we should open an issue to track it and remove these changes when the CI are using `4.3.4`

**Comment by krassowski** [comment]
This should no longer be needed  as 4.3.4 is out and CI elsewhere is confirmed to be passing :)

**Comment by jtpio** [comment]
> This should no longer be needed as 4.3.4 is out and CI elsewhere is confirmed to be passing :)

Confirmed here after restarting a failing check in another PR. Thanks for the fix and the release!

**Comment by brichet** [comment]
Thanks @krassowski and @jtpio.
Closing this as fixed.

**Pull request closed without merging**
